version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name Work5-App --s3-location s3://work5bucket/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src